# Generated by Django 5.2.4 on 2025-08-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
